export default {
    NEWS_ERROR: 'NEWS_ERROR',
    NEWS_REQUEST: 'NEWS_REQUEST',

    GET_ALL_NEWS_ACTION: 'GET_ALL_NEWS_ACTION',
    GET_ALL_NEWS_RESPONSE: 'GET_ALL_NEWS_RESPONSE',
    GET_SINGLE_NEWS_ACTION: 'GET_SINGLE_NEWS_ACTION',
    GET_SINGLE_NEWS_RESPONSE: 'GET_SINGLE_NEWS_ACTION',
    CREATE_NEWS_ACTION: 'CREATE_NEWS_ACTION',
    CREATE_NEWS_RESPONSE: 'CREATE_NEWS_RESPONSE',
    DELETE_NEWS_ACTION: 'DELETE_NEWS_ACTION',
    DELETE_NEWS_RESPONSE: 'DELETE_NEWS_RESPONSE',


    LOGIN_ACTION: 'LOGIN_ACTION',
    LOGIN_RESPONSE: 'LOGIN_RESPONSE',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_ERROR: 'LOGIN_ERROR',

    PRIEST_ERROR: 'PRIEST_ERROR',
    PRIEST_REQUEST: 'PRIEST_REQUEST',

    GET_ALL_PRIEST_ACTION: 'GET_ALL_PRIEST_ACTION',
    GET_ALL_PRIEST_RESPONSE: 'GET_ALL_PRIEST_RESPONSE',
    GET_SINGLE_PRIEST_ACTION: 'GET_SINGLE_PRIEST_ACTION',
    GET_SINGLE_PRIEST_RESPONSE: 'GET_SINGLE_PRIEST_RESPONSE',
    CREATE_PRIEST_ACTION: 'CREATE_PRIEST_ACTION',
    CREATE_PRIEST_RESPONSE: 'CREATE_PRIEST_RESPONSE',
    DELETE_PRIEST_ACTION: 'DELETE_PRIEST_ACTION',
    DELETE_PRIEST_RESPONSE: 'DELETE_PRIEST_RESPONSE',

    MODAL_FORM_CHANGE_STATUS_ACTION: 'MODAL_FORM_CHANGE_STATUS_ACTION',
}
