export default {
    NEWS_ERROR: 'NEWS_ERROR',
    NEWS_REQUEST: 'NEWS_REQUEST',

    GET_ALL_NEWS_ACTION: 'GET_ALL_NEWS_ACTION',
    GET_ALL_NEWS_RESPONSE: 'GET_ALL_NEWS_RESPONSE',

    GET_SINGLE_NEWS_ACTION: 'GET_SINGLE_NEWS_ACTION',
    GET_SINGLE_NEWS_RESPONSE: 'GET_SINGLE_NEWS_ACTION',
}